version: '3'
services:

  mongodb:
    image: 'mongo'
    container_name: 'mongodb-barbershopjs'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ~/mongo-volume:/data/db
      - ~/mongo-config-volume:/data/configdb
    ports:
      - '27017:27017'

  postgres:
    image: 'postgres'
    container_name: 'postgres-barbershopjs'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    container_name: 'redis-barbershopjs'
    volumes:
      - ~/redis-volume:/data
    ports:
      - '6379:6379'

volumes:
  mongo-volume:
  mongo-config-volume:
  postgres-volume:
  redis-volume:
